# notes: c'est le fichier utilisé lors des étapes build et test de gitlab-ci
version: '3.9'

services:
  web:
    build:
      context: ./oc_projet9
      dockerfile: Dockerfile
    stop_grace_period: 10s
    command: gunicorn oc_projet9_appli_web_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    environment:
      - DEBUG
      - SECRET_KEY
      - DJANGO_ALLOWED_HOSTS
      - SQL_ENGINE
      - SQL_DATABASE
      - SQL_USER
      - SQL_PASSWORD
      - SQL_HOST
      - SQL_PORT
      - DATABASE
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 5555:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
