version: '3.9'

services:
  web:
    build:
      context: ./oc_projet9
      dockerfile: Dockerfile
    stop_grace_period: 10s
    command: gunicorn oc_projet9_appli_web_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/dummy-operator/web/staticfiles
      - media_volume:/home/dummy-operator/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/dummy-operator/web/staticfiles
      - media_volume:/home/dummy-operator/web/mediafiles
    ports:
      - 5555:8080
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
