# notes: c'est le fichier utilisé lors des étapes build et test de gitlab-ci
services:
  web:
    build:
      context: ./dummy_app
      dockerfile: Dockerfile
    stop_grace_period: 10s
    container_name: web
    command: gunicorn dummy_app_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/dummy-operator/web/staticfiles
      - media_volume:/home/dummy-operator/web/mediafiles
    expose:
      - 8000
    environment:
      - DEBUG
      - SECRET_KEY
      - DJANGO_ALLOWED_HOSTS
      - SQL_ENGINE
      - SQL_DATABASE
      - SQL_USER
      - SQL_PASSWORD
      - SQL_HOST
      - SQL_PORT
      - DATABASE
    depends_on:
      - db
  db:
    image: postgres:16.0-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/home/dummy-operator/web/staticfiles
      - media_volume:/home/dummy-operator/web/mediafiles
    ports:
      - 5555:8080
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
